# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnp222z61-capi-aws
  namespace: cnp222z61
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cnp222z61-capi-aws
subjects:
- kind: ServiceAccount
  name: cnp222z61-capi-aws
